// src/lib/conferences.ts

export interface ConferenceData {
  [sportKey: string]: {
    [teamName: string]: string;
  };
}

export const CONFERENCES: ConferenceData = {
  americanfootball_ncaaf: {
    // SEC
    "Alabama Crimson Tide": "SEC",
    "Arkansas Razorbacks": "SEC",
    "Auburn Tigers": "SEC",
    "Florida Gators": "SEC",
    "Georgia Bulldogs": "SEC",
    "Kentucky Wildcats": "SEC",
    "LSU Tigers": "SEC",
    "Mississippi State Bulldogs": "SEC",
    "Missouri Tigers": "SEC",
    "Ole Miss Rebels": "SEC",
    "South Carolina Gamecocks": "SEC",
    "Tennessee Volunteers": "SEC",
    "Texas A&M Aggies": "SEC",
    "Vanderbilt Commodores": "SEC",
     "Oklahoma Sooners": "SEC",
      "Texas Longhorns": "SEC",
    
    // Big Ten
    "Illinois Fighting Illini": "Big Ten",
    "Indiana Hoosiers": "Big Ten",
    "Iowa Hawkeyes": "Big Ten",
    "Maryland Terrapins": "Big Ten",
    "Michigan Wolverines": "Big Ten",
    "Michigan State Spartans": "Big Ten",
    "Minnesota Golden Gophers": "Big Ten",
    "Nebraska Cornhuskers": "Big Ten",
    "Northwestern Wildcats": "Big Ten",
    "Ohio State Buckeyes": "Big Ten",
    "Penn State Nittany Lions": "Big Ten",
    "Purdue Boilermakers": "Big Ten",
    "Rutgers Scarlet Knights": "Big Ten",
    "Wisconsin Badgers": "Big Ten",
    "Oregon Ducks": "Big Ten",
    "Washington Huskies": "Big Ten",
    
    // Big 12
    "Baylor Bears": "Big 12",
    "Cincinnati Bearcats": "Big 12",
    "Houston Cougars": "Big 12",
    "Iowa State Cyclones": "Big 12",
    "Kansas Jayhawks": "Big 12",
    "Kansas State Wildcats": "Big 12",
    "Oklahoma State Cowboys": "Big 12",
    "TCU Horned Frogs": "Big 12",
    "Texas Tech Red Raiders": "Big 12",
    "UCF Knights": "Big 12",
    "West Virginia Mountaineers": "Big 12",
    "BYU Cougars": "Big 12",
    "Colorado Buffaloes": "Big 12",
    "Arizona Wildcats": "Big 12",
    "Arizona State Sun Devils": "Big 12",
    "Utah Utes": "Big 12",
    
    // ACC
    "Boston College Eagles": "ACC",
    "Clemson Tigers": "ACC",
    "Duke Blue Devils": "ACC",
    "Florida State Seminoles": "ACC",
    "Georgia Tech Yellow Jackets": "ACC",
    "Louisville Cardinals": "ACC",
    "Miami Hurricanes": "ACC",
    "NC State Wolfpack": "ACC",
    "North Carolina Tar Heels": "ACC",
    "Pittsburgh Panthers": "ACC",
    "Syracuse Orange": "ACC",
    "Virginia Cavaliers": "ACC",
    "Virginia Tech Hokies": "ACC",
    "Wake Forest Demon Deacons": "ACC",
    "SMU Mustangs": "ACC",
    "California Golden Bears": "ACC",
    "Stanford Cardinal": "ACC",
    
    // Pac-12 (legacy/remaining)
    "Oregon State Beavers": "Pac-12",
    "Washington State Cougars": "Pac-12",
    
    // Independent
    "Notre Dame Fighting Irish": "Independent",
    "UConn Huskies": "Independent",
    
    // Mountain West
    "Air Force Falcons": "Mountain West",
    "Boise State Broncos": "Mountain West",
    "Colorado State Rams": "Mountain West",
    "Fresno State Bulldogs": "Mountain West",
    "Hawaii Rainbow Warriors": "Mountain West",
    "Nevada Wolf Pack": "Mountain West",
    "New Mexico Lobos": "Mountain West",
    "San Diego State Aztecs": "Mountain West",
    "San Jose State Spartans": "Mountain West",
    "UNLV Rebels": "Mountain West",
    "Utah State Aggies": "Mountain West",
    "Wyoming Cowboys": "Mountain West",
    
    // American
    "Army Black Knights": "American",
    "Charlotte 49ers": "American",
    "East Carolina Pirates": "American",
    "FAU Owls": "American",
    "Memphis Tigers": "American",
    "Navy Midshipmen": "American",
    "Rice Owls": "American",
    "South Florida Bulls": "American",
    "Temple Owls": "American",
    "Tulane Green Wave": "American",
    "Tulsa Golden Hurricane": "American",
    "UAB Blazers": "American",
    "UTSA Roadrunners": "American",
    "North Texas Mean Green": "American",
    
    // Sun Belt
    "Appalachian State Mountaineers": "Sun Belt",
    "Arkansas State Red Wolves": "Sun Belt",
    "Coastal Carolina Chanticleers": "Sun Belt",
    "Georgia Southern Eagles": "Sun Belt",
    "Georgia State Panthers": "Sun Belt",
    "James Madison Dukes": "Sun Belt",
    "Louisiana Ragin' Cajuns": "Sun Belt",
    "Marshall Thundering Herd": "Sun Belt",
    "Old Dominion Monarchs": "Sun Belt",
    "South Alabama Jaguars": "Sun Belt",
    "Southern Miss Golden Eagles": "Sun Belt",
    "Texas State Bobcats": "Sun Belt",
    "Troy Trojans": "Sun Belt",
    "UL Monroe Warhawks": "Sun Belt",
    
    // Conference USA
    "FIU Panthers": "Conference USA",
    "Jacksonville State Gamecocks": "Conference USA",
    "Liberty Flames": "Conference USA",
    "Louisiana Tech Bulldogs": "Conference USA",
    "Middle Tennessee Blue Raiders": "Conference USA",
    "New Mexico State Aggies": "Conference USA",
    "Sam Houston Bearkats": "Conference USA",
    "UTEP Miners": "Conference USA",
    "Western Kentucky Hilltoppers": "Conference USA",
    "Delaware Blue Hens": "Conference USA",
    "Kennesaw State Owls": "Conference USA",
    "Missouri State Bears": "Conference USA",
    
    // MAC
    "Akron Zips": "MAC",
    "Ball State Cardinals": "MAC",
    "Bowling Green Falcons": "MAC",
    "Buffalo Bulls": "MAC",
    "Central Michigan Chippewas": "MAC",
    "Eastern Michigan Eagles": "MAC",
    "Kent State Golden Flashes": "MAC",
    "Miami (OH) RedHawks": "MAC",
    "Northern Illinois Huskies": "MAC",
    "Ohio Bobcats": "MAC",
    "Toledo Rockets": "MAC",
    "Western Michigan Broncos": "MAC",
    "UMass Minutemen": "MAC",
  },
  
  basketball_ncaab: {
    // ACC
    "Boston College Eagles": "ACC",
    "Clemson Tigers": "ACC",
    "Duke Blue Devils": "ACC",
    "Florida State Seminoles": "ACC",
    "Georgia Tech Yellow Jackets": "ACC",
    "Louisville Cardinals": "ACC",
    "Miami Hurricanes": "ACC",
    "NC State Wolfpack": "ACC",
    "North Carolina Tar Heels": "ACC",
    "Notre Dame Fighting Irish": "ACC",
    "Pittsburgh Panthers": "ACC",
    "Syracuse Orange": "ACC",
    "Virginia Cavaliers": "ACC",
    "Virginia Tech Hokies": "ACC",
    "Wake Forest Demon Deacons": "ACC",
    "SMU Mustangs": "ACC",
    "California Golden Bears": "ACC",
    "Stanford Cardinal": "ACC",
    
    // Big Ten
    "Illinois Fighting Illini": "Big Ten",
    "Indiana Hoosiers": "Big Ten",
    "Iowa Hawkeyes": "Big Ten",
    "Maryland Terrapins": "Big Ten",
    "Michigan Wolverines": "Big Ten",
    "Michigan State Spartans": "Big Ten",
    "Minnesota Golden Gophers": "Big Ten",
    "Nebraska Cornhuskers": "Big Ten",
    "Northwestern Wildcats": "Big Ten",
    "Ohio State Buckeyes": "Big Ten",
    "Penn State Nittany Lions": "Big Ten",
    "Purdue Boilermakers": "Big Ten",
    "Rutgers Scarlet Knights": "Big Ten",
    "Wisconsin Badgers": "Big Ten",
    "Oregon Ducks": "Big Ten",
    "Washington Huskies": "Big Ten",
    "UCLA Bruins": "Big Ten",
    "USC Trojans": "Big Ten",
    
    // Big 12
    "Arizona Wildcats": "Big 12",
    "Arizona State Sun Devils": "Big 12",
    "Baylor Bears": "Big 12",
    "BYU Cougars": "Big 12",
    "Cincinnati Bearcats": "Big 12",
    "Colorado Buffaloes": "Big 12",
    "Houston Cougars": "Big 12",
    "Iowa State Cyclones": "Big 12",
    "Kansas Jayhawks": "Big 12",
    "Kansas State Wildcats": "Big 12",
    "Oklahoma State Cowboys": "Big 12",
    "TCU Horned Frogs": "Big 12",
    "Texas Tech Red Raiders": "Big 12",
    "UCF Knights": "Big 12",
    "Utah Utes": "Big 12",
    "West Virginia Mountaineers": "Big 12",
    
    // SEC
    "Alabama Crimson Tide": "SEC",
    "Arkansas Razorbacks": "SEC",
    "Auburn Tigers": "SEC",
    "Florida Gators": "SEC",
    "Georgia Bulldogs": "SEC",
    "Kentucky Wildcats": "SEC",
    "LSU Tigers": "SEC",
    "Mississippi State Bulldogs": "SEC",
    "Missouri Tigers": "SEC",
    "Ole Miss Rebels": "SEC",
    "Oklahoma Sooners": "SEC",
    "South Carolina Gamecocks": "SEC",
    "Tennessee Volunteers": "SEC",
    "Texas A&M Aggies": "SEC",
    "Texas Longhorns": "SEC",
    "Vanderbilt Commodores": "SEC",
    
    // Big East
    "Butler Bulldogs": "Big East",
    "Creighton Bluejays": "Big East",
    "DePaul Blue Demons": "Big East",
    "Georgetown Hoyas": "Big East",
    "Marquette Golden Eagles": "Big East",
    "Providence Friars": "Big East",
    "St. John's Red Storm": "Big East",
    "Seton Hall Pirates": "Big East",
    "UConn Huskies": "Big East",
    "Villanova Wildcats": "Big East",
    "Xavier Musketeers": "Big East",
    
    // American Athletic Conference
    "Charlotte 49ers": "American",
    "East Carolina Pirates": "American",
    "FAU Owls": "American",
    "Memphis Tigers": "American",
    "Navy Midshipmen": "American",
    "North Texas Mean Green": "American",
    "Rice Owls": "American",
    "South Florida Bulls": "American",
    "Temple Owls": "American",
    "Tulane Green Wave": "American",
    "Tulsa Golden Hurricane": "American",
    "UAB Blazers": "American",
    "UTSA Roadrunners": "American",
    "Army Black Knights": "American",
    
    // Mountain West
    "Air Force Falcons": "Mountain West",
    "Boise State Broncos": "Mountain West",
    "Colorado State Rams": "Mountain West",
    "Fresno State Bulldogs": "Mountain West",
    "Nevada Wolf Pack": "Mountain West",
    "New Mexico Lobos": "Mountain West",
    "San Diego State Aztecs": "Mountain West",
    "San Jose State Spartans": "Mountain West",
    "UNLV Rebels": "Mountain West",
    "Utah State Aggies": "Mountain West",
    "Wyoming Cowboys": "Mountain West",
    
    // Atlantic 10
    "Davidson Wildcats": "Atlantic 10",
    "Dayton Flyers": "Atlantic 10",
    "Duquesne Dukes": "Atlantic 10",
    "Fordham Rams": "Atlantic 10",
    "George Mason Patriots": "Atlantic 10",
    "George Washington Colonials": "Atlantic 10",
    "La Salle Explorers": "Atlantic 10",
    "Loyola Chicago Ramblers": "Atlantic 10",
    "UMass Minutemen": "Atlantic 10",
    "Rhode Island Rams": "Atlantic 10",
    "Richmond Spiders": "Atlantic 10",
    "St. Bonaventure Bonnies": "Atlantic 10",
    "Saint Joseph's Hawks": "Atlantic 10",
    "Saint Louis Billikens": "Atlantic 10",
    "VCU Rams": "Atlantic 10",
    
    // West Coast Conference
    "Gonzaga Bulldogs": "WCC",
    "Loyola Marymount Lions": "WCC",
    "Pacific Tigers": "WCC",
    "Pepperdine Waves": "WCC",
    "Portland Pilots": "WCC",
    "Saint Mary's Gaels": "WCC",
    "San Diego Toreros": "WCC",
    "San Francisco Dons": "WCC",
    "Santa Clara Broncos": "WCC",
    "Washington State Cougars": "WCC",
    "Oregon State Beavers": "WCC",
    
    // Missouri Valley Conference
    "Bradley Braves": "Missouri Valley",
    "Drake Bulldogs": "Missouri Valley",
    "Illinois State Redbirds": "Missouri Valley",
    "Indiana State Sycamores": "Missouri Valley",
    "Missouri State Bears": "Missouri Valley",
    "Murray State Racers": "Missouri Valley",
    "Northern Iowa Panthers": "Missouri Valley",
    "Southern Illinois Salukis": "Missouri Valley",
    "UIC Flames": "Missouri Valley",
    "Valparaiso Beacons": "Missouri Valley",
    "Belmont Bruins": "Missouri Valley",
    
    // Conference USA
    "FIU Panthers": "Conference USA",
    "Jacksonville State Gamecocks": "Conference USA",
    "Liberty Flames": "Conference USA",
    "Louisiana Tech Bulldogs": "Conference USA",
    "Middle Tennessee Blue Raiders": "Conference USA",
    "New Mexico State Aggies": "Conference USA",
    "Sam Houston Bearkats": "Conference USA",
    "UTEP Miners": "Conference USA",
    "Western Kentucky Hilltoppers": "Conference USA",
    "Kennesaw State Owls": "Conference USA",
    
    // Sun Belt
    "Appalachian State Mountaineers": "Sun Belt",
    "Arkansas State Red Wolves": "Sun Belt",
    "Coastal Carolina Chanticleers": "Sun Belt",
    "Georgia Southern Eagles": "Sun Belt",
    "Georgia State Panthers": "Sun Belt",
    "James Madison Dukes": "Sun Belt",
    "Louisiana Ragin' Cajuns": "Sun Belt",
    "Marshall Thundering Herd": "Sun Belt",
    "Old Dominion Monarchs": "Sun Belt",
    "South Alabama Jaguars": "Sun Belt",
    "Southern Miss Golden Eagles": "Sun Belt",
    "Texas State Bobcats": "Sun Belt",
    "Troy Trojans": "Sun Belt",
    "UL Monroe Warhawks": "Sun Belt",
    
    // MAC
    "Akron Zips": "MAC",
    "Ball State Cardinals": "MAC",
    "Bowling Green Falcons": "MAC",
    "Buffalo Bulls": "MAC",
    "Central Michigan Chippewas": "MAC",
    "Eastern Michigan Eagles": "MAC",
    "Kent State Golden Flashes": "MAC",
    "Miami (OH) RedHawks": "MAC",
    "Northern Illinois Huskies": "MAC",
    "Ohio Bobcats": "MAC",
    "Toledo Rockets": "MAC",
    "Western Michigan Broncos": "MAC",
    
    // Ivy League
    "Brown Bears": "Ivy League",
    "Columbia Lions": "Ivy League",
    "Cornell Big Red": "Ivy League",
    "Dartmouth Big Green": "Ivy League",
    "Harvard Crimson": "Ivy League",
    "Penn Quakers": "Ivy League",
    "Princeton Tigers": "Ivy League",
    "Yale Bulldogs": "Ivy League",
    
    // Big Sky
    "Eastern Washington Eagles": "Big Sky",
    "Idaho Vandals": "Big Sky",
    "Idaho State Bengals": "Big Sky",
    "Montana Grizzlies": "Big Sky",
    "Montana State Bobcats": "Big Sky",
    "Northern Arizona Lumberjacks": "Big Sky",
    "Northern Colorado Bears": "Big Sky",
    "Portland State Vikings": "Big Sky",
    "Sacramento State Hornets": "Big Sky",
    "Weber State Wildcats": "Big Sky",
    
    // Horizon League
    "Cleveland State Vikings": "Horizon League",
    "Detroit Mercy Titans": "Horizon League",
    "Green Bay Phoenix": "Horizon League",
    "Milwaukee Panthers": "Horizon League",
    "Northern Kentucky Norse": "Horizon League",
    "Oakland Golden Grizzlies": "Horizon League",
    "Purdue Fort Wayne Mastodons": "Horizon League",
    "Robert Morris Colonials": "Horizon League",
    "Wright State Raiders": "Horizon League",
    "Youngstown State Penguins": "Horizon League",
    
    // Colonial Athletic Association
    "Charleston Cougars": "Colonial",
    "Delaware Blue Hens": "Colonial",
    "Drexel Dragons": "Colonial",
    "Elon Phoenix": "Colonial",
    "Hampton Pirates": "Colonial",
    "Hofstra Pride": "Colonial",
    "Monmouth Hawks": "Colonial",
    "North Carolina A&T Aggies": "Colonial",
    "Northeastern Huskies": "Colonial",
    "Stony Brook Seawolves": "Colonial",
    "Towson Tigers": "Colonial",
    "UNC Wilmington Seahawks": "Colonial",
    "William & Mary Tribe": "Colonial",
    
    // Southern Conference
    "Chattanooga Mocs": "Southern",
    "The Citadel Bulldogs": "Southern",
    "East Tennessee State Buccaneers": "Southern",
    "Furman Paladins": "Southern",
    "Mercer Bears": "Southern",
    "Samford Bulldogs": "Southern",
    "UNC Greensboro Spartans": "Southern",
    "VMI Keydets": "Southern",
    "Western Carolina Catamounts": "Southern",
    "Wofford Terriers": "Southern",
    
    // Patriot League
    "American Eagles": "Patriot League",
    "Army Black Knights": "Patriot League",
    "Boston University Terriers": "Patriot League",
    "Bucknell Bison": "Patriot League",
    "Colgate Raiders": "Patriot League",
    "Holy Cross Crusaders": "Patriot League",
    "Lafayette Leopards": "Patriot League",
    "Lehigh Mountain Hawks": "Patriot League",
    "Loyola Maryland Greyhounds": "Patriot League",
    "Navy Midshipmen": "Patriot League",
    
    // MAAC
    "Canisius Golden Griffins": "MAAC",
    "Fairfield Stags": "MAAC",
    "Iona Gaels": "MAAC",
    "Manhattan Jaspers": "MAAC",
    "Marist Red Foxes": "MAAC",
    "Mount St. Mary's Mountaineers": "MAAC",
    "Niagara Purple Eagles": "MAAC",
    "Quinnipiac Bobcats": "MAAC",
    "Rider Broncs": "MAAC",
    "Saint Peter's Peacocks": "MAAC",
    "Siena Saints": "MAAC",
    
    // Summit League
    "Denver Pioneers": "Summit League",
    "Kansas City Roos": "Summit League",
    "North Dakota Fighting Hawks": "Summit League",
    "North Dakota State Bison": "Summit League",
    "Omaha Mavericks": "Summit League",
    "Oral Roberts Golden Eagles": "Summit League",
    "South Dakota Coyotes": "Summit League",
    "South Dakota State Jackrabbits": "Summit League",
    "St. Thomas Tommies": "Summit League",
    
    // WAC
    "Abilene Christian Wildcats": "WAC",
    "California Baptist Lancers": "WAC",
    "Grand Canyon Antelopes": "WAC",
    "Seattle U Redhawks": "WAC",
    "Southern Utah Thunderbirds": "WAC",
    "Stephen F. Austin Lumberjacks": "WAC",
    "Tarleton State Texans": "WAC",
    "UT Arlington Mavericks": "WAC",
    "Utah Tech Trailblazers": "WAC",
    "Utah Valley Wolverines": "WAC",
    
    // Big South
    "Campbell Fighting Camels": "Big South",
    "Charleston Southern Buccaneers": "Big South",
    "Gardner-Webb Bulldogs": "Big South",
    "High Point Panthers": "Big South",
    "Longwood Lancers": "Big South",
    "Presbyterian Blue Hose": "Big South",
    "Radford Highlanders": "Big South",
    "South Carolina Upstate Spartans": "Big South",
    "UNC Asheville Bulldogs": "Big South",
    "Winthrop Eagles": "Big South",
    
    // Southland
    "Houston Christian Huskies": "Southland",
    "Incarnate Word Cardinals": "Southland",
    "Lamar Cardinals": "Southland",
    "McNeese Cowboys": "Southland",
    "New Orleans Privateers": "Southland",
    "Nicholls Colonels": "Southland",
    "Northwestern State Demons": "Southland",
    "SE Louisiana Lions": "Southland",
    "Texas A&M-CC Islanders": "Southland",
    
    // SWAC
    "Alabama A&M Bulldogs": "SWAC",
    "Alabama State Hornets": "SWAC",
    "Alcorn State Braves": "SWAC",
    "Arkansas-Pine Bluff Golden Lions": "SWAC",
    "Bethune-Cookman Wildcats": "SWAC",
    "Florida A&M Rattlers": "SWAC",
    "Grambling State Tigers": "SWAC",
    "Jackson State Tigers": "SWAC",
    "Mississippi Valley State Delta Devils": "SWAC",
    "Prairie View A&M Panthers": "SWAC",
    "Southern Jaguars": "SWAC",
    "Texas Southern Tigers": "SWAC",
    
    // MEAC
    "Coppin State Eagles": "MEAC",
    "Delaware State Hornets": "MEAC",
    "Howard Bison": "MEAC",
    "Maryland Eastern Shore Hawks": "MEAC",
    "Morgan State Bears": "MEAC",
    "Norfolk State Spartans": "MEAC",
    "North Carolina Central Eagles": "MEAC",
    "South Carolina State Bulldogs": "MEAC",
    
    // Ohio Valley
    "Eastern Illinois Panthers": "Ohio Valley",
    "Lindenwood Lions": "Ohio Valley",
    "Little Rock Trojans": "Ohio Valley",
    "Morehead State Eagles": "Ohio Valley",
    "SIU Edwardsville Cougars": "Ohio Valley",
    "Southern Indiana Screaming Eagles": "Ohio Valley",
    "Tennessee State Tigers": "Ohio Valley",
    "Tennessee Tech Golden Eagles": "Ohio Valley",
    "UT Martin Skyhawks": "Ohio Valley",
    "Western Illinois Leathernecks": "Ohio Valley",
    
    // America East
    "Binghamton Bearcats": "America East",
    "Bryant Bulldogs": "America East",
    "Maine Black Bears": "America East",
    "New Hampshire Wildcats": "America East",
    "NJIT Highlanders": "America East",
    "UAlbany Great Danes": "America East",
    "UMass Lowell River Hawks": "America East",
    "UMBC Retrievers": "America East",
    "Vermont Catamounts": "America East",
    
    // Northeast Conference
    "Central Connecticut Blue Devils": "NEC",
    "Fairleigh Dickinson Knights": "NEC",
    "LIU Sharks": "NEC",
    "Merrimack Warriors": "NEC",
    "Sacred Heart Pioneers": "NEC",
    "St. Francis Brooklyn Terriers": "NEC",
    "Stonehill Skyhawks": "NEC",
    "Wagner Seahawks": "NEC",
  }
};

// Helper function to get unique conferences for a sport
export function getConferencesForSport(sportKey: string): string[] {
  const sportConferences = CONFERENCES[sportKey];
  if (!sportConferences) return [];
  
  const uniqueConferences = new Set(Object.values(sportConferences));
  return Array.from(uniqueConferences).sort();
}

// Helper function to get conference for a team
export function getTeamConference(sportKey: string, teamName: string): string | null {
  return CONFERENCES[sportKey]?.[teamName] || null;
}