-- FBS market-driven power ratings system
-- Seeded from the Brad Powers rating set (power_rating_sets), then adjusted
-- by closing lines: adjustment = (closing - projected) / 2, zero-sum.
-- Run this in the Supabase SQL editor before first use.

create table if not exists fbs_ratings (
  id bigint generated by default as identity primary key,
  team_name text not null,            -- canonical name (ESPN location, e.g. "Ohio State")
  powers_name text not null,          -- name as it appears in the Brad Powers set
  espn_name text,                     -- ESPN displayName ("Ohio State Buckeyes")
  espn_id text,                       -- ESPN team id
  conference text,
  rating numeric not null,            -- current market-adjusted rating (neutral floor, points)
  initial_rating numeric not null,    -- Brad Powers rating at seed time
  hfa numeric,                        -- per-team home field advantage (from Brad Powers)
  games_processed integer not null default 0,
  season integer not null,
  updated_at timestamptz not null default now(),
  unique (team_name, season),
  unique (powers_name, season)
);

create table if not exists fbs_game_adjustments (
  game_id text primary key,           -- ESPN event id
  odds_api_id text,
  game_date timestamptz not null,
  home_team text not null,            -- canonical names (fbs_ratings.team_name)
  away_team text not null,
  is_neutral_site boolean not null default false,
  hfa_applied numeric not null default 0,
  projected_spread numeric not null,  -- home perspective, negative = home favored
  closing_spread numeric not null,
  closing_source text,
  difference numeric not null,        -- closing - projected
  adjustment numeric not null,        -- difference / 2 (away +=, home -=)
  home_rating_before numeric not null,
  home_rating_after numeric not null,
  away_rating_before numeric not null,
  away_rating_after numeric not null,
  season integer not null,
  processed_at timestamptz not null default now()
);

create index if not exists fbs_game_adjustments_date_idx
  on fbs_game_adjustments (season, game_date);

-- Per-game closing line cache (also caches "no line available" as null spread
-- so we never re-burn historical Odds API credits on unlined games).
create table if not exists fbs_closing_lines (
  game_id text primary key,           -- ESPN event id
  odds_api_id text,
  game_date timestamptz,
  home_team text,
  away_team text,
  is_neutral_site boolean not null default false,
  closing_spread numeric,             -- null = checked, no line found
  closing_source text,
  bookmakers text[],
  fetched_at timestamptz not null default now()
);

create table if not exists fbs_ratings_config (
  id integer primary key,
  hfa_default numeric not null default 3.0,
  closing_source text not null default 'us_average',
  season integer not null,
  last_processed_date date,
  updated_at timestamptz not null default now()
);

insert into fbs_ratings_config (id, season) values (1, 2026)
on conflict (id) do nothing;

-- Manual rating adjustments — dated, replayable ledger entries. delta applies
-- to one team (not zero-sum); replay merges these with game adjustments
-- chronologically. rating_before/after + applied_at are stamped by the
-- replay; updated_at > applied_at (or null applied_at) = not yet applied.
create table if not exists fbs_manual_adjustments (
  id bigint generated by default as identity primary key,
  team_name text not null,
  season integer not null,
  adjust_date timestamptz not null default now(),
  delta numeric not null,
  note text,
  rating_before numeric,
  rating_after numeric,
  applied_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists fbs_manual_adjustments_season_idx
  on fbs_manual_adjustments (season, adjust_date);
