-- FCS market-driven power ratings system
-- Seeded from Massey FCS "Pwr" ratings, then adjusted by closing lines:
-- adjustment = (closing - projected) / 2, applied zero-sum to both teams.
-- Run this in the Supabase SQL editor before first use.

create table if not exists fcs_ratings (
  id bigint generated by default as identity primary key,
  team_name text not null,            -- canonical name (ESPN location, e.g. "South Dakota State")
  massey_name text not null,          -- name as shown on masseyratings.com ("S Dakota St")
  espn_name text,                     -- ESPN displayName ("South Dakota State Jackrabbits")
  espn_id text,                       -- ESPN team id
  conference text,
  rating numeric not null,            -- current market-adjusted rating (neutral floor, points)
  initial_rating numeric not null,    -- Massey Pwr at seed time
  hfa numeric,                        -- per-team home field advantage (from Massey)
  games_processed integer not null default 0,
  season integer not null,
  updated_at timestamptz not null default now(),
  unique (team_name, season),
  unique (massey_name, season)
);

create table if not exists fcs_game_adjustments (
  game_id text primary key,           -- ESPN event id
  odds_api_id text,
  game_date timestamptz not null,
  home_team text not null,            -- canonical names (fcs_ratings.team_name)
  away_team text not null,
  is_neutral_site boolean not null default false,
  hfa_applied numeric not null default 0,
  projected_spread numeric not null,  -- home perspective, negative = home favored
  closing_spread numeric not null,
  closing_source text,
  difference numeric not null,        -- closing - projected
  adjustment numeric not null,        -- difference / 2 (away +=, home -=)
  home_rating_before numeric not null,
  home_rating_after numeric not null,
  away_rating_before numeric not null,
  away_rating_after numeric not null,
  season integer not null,
  processed_at timestamptz not null default now()
);

create index if not exists fcs_game_adjustments_date_idx
  on fcs_game_adjustments (season, game_date);

-- Per-game closing line cache (also caches "no line available" as null spread
-- so we never re-burn historical Odds API credits on unlined games).
create table if not exists fcs_closing_lines (
  game_id text primary key,           -- ESPN event id
  odds_api_id text,
  game_date timestamptz,
  home_team text,
  away_team text,
  closing_spread numeric,             -- null = checked, no line found
  closing_source text,
  bookmakers text[],
  fetched_at timestamptz not null default now()
);

create table if not exists fcs_ratings_config (
  id integer primary key,
  hfa_default numeric not null default 2.5,
  closing_source text not null default 'us_average',
  season integer not null,
  last_processed_date date,
  updated_at timestamptz not null default now()
);

insert into fcs_ratings_config (id, season) values (1, 2026)
on conflict (id) do nothing;

-- 2026-08-27: neutral-site flag on the line cache so manually-lined games
-- processed after the fact still apply the right HFA.
alter table fcs_closing_lines add column if not exists is_neutral_site boolean not null default false;
