-- NFL Ledger ratings system
-- Seeded from the market-implied fit stored in power_rating_sets (sport 'nfl',
-- source 'market_fit' — written by POST /api/nfl/seed), then adjusted by
-- closing lines: adjustment = (closing - projected) / 2, zero-sum.
-- Run this in the Supabase SQL editor before first use.

create table if not exists nfl_ratings (
  id bigint generated by default as identity primary key,
  team_name text not null,            -- canonical name (ESPN displayName, e.g. "Kansas City Chiefs")
  seed_name text not null,            -- name as it appears in the seed set
  espn_name text,                     -- ESPN displayName
  espn_id text,                       -- ESPN team id
  espn_abbr text,                     -- ESPN abbreviation ("KC") — logos key off this
  conference text,                    -- division ("AFC West")
  rating numeric not null,            -- current market-adjusted rating (points vs league average)
  initial_rating numeric not null,    -- seed rating
  hfa numeric,                        -- per-team home field advantage (null = config default)
  games_processed integer not null default 0,
  season integer not null,
  updated_at timestamptz not null default now(),
  unique (team_name, season),
  unique (seed_name, season)
);

create table if not exists nfl_game_adjustments (
  game_id text primary key,           -- ESPN event id
  odds_api_id text,
  game_date timestamptz not null,
  home_team text not null,            -- canonical names (nfl_ratings.team_name)
  away_team text not null,
  is_neutral_site boolean not null default false,
  hfa_applied numeric not null default 0,
  projected_spread numeric not null,  -- home perspective, negative = home favored
  closing_spread numeric not null,
  closing_source text,
  difference numeric not null,        -- closing - projected
  adjustment numeric not null,        -- difference / 2 (away +=, home -=)
  home_rating_before numeric not null,
  home_rating_after numeric not null,
  away_rating_before numeric not null,
  away_rating_after numeric not null,
  season integer not null,
  processed_at timestamptz not null default now()
);

create index if not exists nfl_game_adjustments_date_idx
  on nfl_game_adjustments (season, game_date);

-- Per-game closing line cache (also caches "no line available" as null spread
-- so we never re-burn historical Odds API credits on unlined games).
create table if not exists nfl_closing_lines (
  game_id text primary key,           -- ESPN event id
  odds_api_id text,
  game_date timestamptz,
  home_team text,
  away_team text,
  is_neutral_site boolean not null default false,
  closing_spread numeric,             -- null = checked, no line found
  closing_source text,
  bookmakers text[],
  fetched_at timestamptz not null default now()
);

create table if not exists nfl_ratings_config (
  id integer primary key,
  hfa_default numeric not null default 1.5,
  closing_source text not null default 'us_average',
  season integer not null,
  last_processed_date date,
  updated_at timestamptz not null default now()
);

insert into nfl_ratings_config (id, season) values (1, 2026)
on conflict (id) do nothing;

-- Manual rating adjustments — dated, replayable ledger entries (see FBS twin).
create table if not exists nfl_manual_adjustments (
  id bigint generated by default as identity primary key,
  team_name text not null,
  season integer not null,
  adjust_date timestamptz not null default now(),
  delta numeric not null,
  note text,
  rating_before numeric,
  rating_after numeric,
  applied_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists nfl_manual_adjustments_season_idx
  on nfl_manual_adjustments (season, adjust_date);
